# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f40d2aa7ed2293b822d1daf451abe82c83bbb2abc031c1ab4e42579b2aa9e5539578a9c2e73c0d56ea24af6e07862e2ed2586acfa8167e96800454fafed03cc5

test:
  secret_key_base: e3f94344d1557364b2acc0b31f2e631a19c2aa6d06b95cc19b10d6721cd7c752b3b205ada60f89c35956fd683e24e85bb1ac9a095646d727c42412b1faa74b4e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
